// This file will be generated by: npx supabase gen types typescript --project-id YOUR_PROJECT_ID --schema public > src/lib/types/database.ts
// For now, we'll create a placeholder structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          role: 'client' | 'provider' | 'admin'
          full_name: string
          email: string
          avatar_url: string | null
          phone: string | null
          city: string | null
          bio: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          role?: 'client' | 'provider' | 'admin'
          full_name: string
          email: string
          avatar_url?: string | null
          phone?: string | null
          city?: string | null
          bio?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          role?: 'client' | 'provider' | 'admin'
          full_name?: string
          email?: string
          avatar_url?: string | null
          phone?: string | null
          city?: string | null
          bio?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      provider_profiles: {
        Row: {
          id: string
          categories: string[]
          portfolio_urls: string[]
          portfolio_image_urls: string[]
          years_experience: number
          hourly_rate: number | null
          daily_rate: number | null
          is_available: boolean
          instagram_url: string | null
          youtube_url: string | null
          website_url: string | null
          kyc_status: 'pending' | 'submitted' | 'approved' | 'rejected'
          kyc_document_url: string | null
          kyc_rejection_reason: string | null
          rating: number
          total_reviews: number
          total_projects: number
          total_earnings: number
          is_featured: boolean
          razorpay_contact_id: string | null
          razorpay_fund_account_id: string | null
          bank_account_number: string | null
          bank_ifsc: string | null
          bank_account_name: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          categories?: string[]
          portfolio_urls?: string[]
          portfolio_image_urls?: string[]
          years_experience?: number
          hourly_rate?: number | null
          daily_rate?: number | null
          is_available?: boolean
          instagram_url?: string | null
          youtube_url?: string | null
          website_url?: string | null
          kyc_status?: 'pending' | 'submitted' | 'approved' | 'rejected'
          kyc_document_url?: string | null
          kyc_rejection_reason?: string | null
          rating?: number
          total_reviews?: number
          total_projects?: number
          total_earnings?: number
          is_featured?: boolean
          razorpay_contact_id?: string | null
          razorpay_fund_account_id?: string | null
          bank_account_number?: string | null
          bank_ifsc?: string | null
          bank_account_name?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          categories?: string[]
          portfolio_urls?: string[]
          portfolio_image_urls?: string[]
          years_experience?: number
          hourly_rate?: number | null
          daily_rate?: number | null
          is_available?: boolean
          instagram_url?: string | null
          youtube_url?: string | null
          website_url?: string | null
          kyc_status?: 'pending' | 'submitted' | 'approved' | 'rejected'
          kyc_document_url?: string | null
          kyc_rejection_reason?: string | null
          rating?: number
          total_reviews?: number
          total_projects?: number
          total_earnings?: number
          is_featured?: boolean
          razorpay_contact_id?: string | null
          razorpay_fund_account_id?: string | null
          bank_account_number?: string | null
          bank_ifsc?: string | null
          bank_account_name?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          client_id: string
          title: string
          description: string
          category: string
          budget_min: number | null
          budget_max: number | null
          location: string | null
          is_remote: boolean
          event_date: string | null
          duration_hours: number | null
          status: 'open' | 'matched' | 'in_progress' | 'completed' | 'cancelled'
          requirements: Json
          skills_needed: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          client_id: string
          title: string
          description: string
          category: string
          budget_min?: number | null
          budget_max?: number | null
          location?: string | null
          is_remote?: boolean
          event_date?: string | null
          duration_hours?: number | null
          status?: 'open' | 'matched' | 'in_progress' | 'completed' | 'cancelled'
          requirements?: Json
          skills_needed?: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          client_id?: string
          title?: string
          description?: string
          category?: string
          budget_min?: number | null
          budget_max?: number | null
          location?: string | null
          is_remote?: boolean
          event_date?: string | null
          duration_hours?: number | null
          status?: 'open' | 'matched' | 'in_progress' | 'completed' | 'cancelled'
          requirements?: Json
          skills_needed?: string[]
          created_at?: string
          updated_at?: string
        }
      }
      bookings: {
        Row: {
          id: string
          project_id: string | null
          client_id: string
          provider_id: string
          status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'disputed' | 'cancelled'
          payment_status: 'deposit_paid' | 'fully_paid' | 'refunded' | 'pending'
          total_amount: number
          deposit_amount: number
          remaining_amount: number
          platform_fee: number
          razorpay_order_id_deposit: string | null
          razorpay_payment_id_deposit: string | null
          razorpay_order_id_remaining: string | null
          razorpay_payment_id_remaining: string | null
          scheduled_date: string | null
          scheduled_time: string | null
          delivery_deadline: string | null
          notes: string | null
          client_work_approved: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          project_id?: string | null
          client_id: string
          provider_id: string
          status?: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'disputed' | 'cancelled'
          payment_status?: 'deposit_paid' | 'fully_paid' | 'refunded' | 'pending'
          total_amount: number
          deposit_amount: number
          remaining_amount: number
          platform_fee?: number
          razorpay_order_id_deposit?: string | null
          razorpay_payment_id_deposit?: string | null
          razorpay_order_id_remaining?: string | null
          razorpay_payment_id_remaining?: string | null
          scheduled_date?: string | null
          scheduled_time?: string | null
          delivery_deadline?: string | null
          notes?: string | null
          client_work_approved?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          project_id?: string | null
          client_id?: string
          provider_id?: string
          status?: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'disputed' | 'cancelled'
          payment_status?: 'deposit_paid' | 'fully_paid' | 'refunded' | 'pending'
          total_amount?: number
          deposit_amount?: number
          remaining_amount?: number
          platform_fee?: number
          razorpay_order_id_deposit?: string | null
          razorpay_payment_id_deposit?: string | null
          razorpay_order_id_remaining?: string | null
          razorpay_payment_id_remaining?: string | null
          scheduled_date?: string | null
          scheduled_time?: string | null
          delivery_deadline?: string | null
          notes?: string | null
          client_work_approved?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      reviews: {
        Row: {
          id: string
          booking_id: string
          reviewer_id: string
          provider_id: string
          rating: number
          comment: string | null
          created_at: string
        }
        Insert: {
          id?: string
          booking_id: string
          reviewer_id: string
          provider_id: string
          rating: number
          comment?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          booking_id?: string
          reviewer_id?: string
          provider_id?: string
          rating?: number
          comment?: string | null
          created_at?: string
        }
      }
      messages: {
        Row: {
          id: string
          booking_id: string
          sender_id: string
          content: string
          attachment_url: string | null
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          booking_id: string
          sender_id: string
          content: string
          attachment_url?: string | null
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          booking_id?: string
          sender_id?: string
          content?: string
          attachment_url?: string | null
          is_read?: boolean
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          title: string
          body: string
          type: 'booking' | 'message' | 'payment' | 'kyc' | 'match' | 'review' | 'general'
          is_read: boolean
          action_url: string | null
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          body: string
          type?: 'booking' | 'message' | 'payment' | 'kyc' | 'match' | 'review' | 'general'
          is_read?: boolean
          action_url?: string | null
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          body?: string
          type?: 'booking' | 'message' | 'payment' | 'kyc' | 'match' | 'review' | 'general'
          is_read?: boolean
          action_url?: string | null
          metadata?: Json
          created_at?: string
        }
      }
      project_interests: {
        Row: {
          id: string
          project_id: string
          provider_id: string
          cover_note: string | null
          proposed_rate: number | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          provider_id: string
          cover_note?: string | null
          proposed_rate?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          provider_id?: string
          cover_note?: string | null
          proposed_rate?: number | null
          created_at?: string
        }
      }
      match_requests: {
        Row: {
          id: string
          project_id: string | null
          client_id: string | null
          matched_provider_ids: string[]
          match_scores: Json
          match_reasons: Json
          created_at: string
        }
        Insert: {
          id?: string
          project_id?: string | null
          client_id?: string | null
          matched_provider_ids?: string[]
          match_scores?: Json
          match_reasons?: Json
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string | null
          client_id?: string | null
          matched_provider_ids?: string[]
          match_scores?: Json
          match_reasons?: Json
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'client' | 'provider' | 'admin'
      kyc_status: 'pending' | 'submitted' | 'approved' | 'rejected'
      project_status: 'open' | 'matched' | 'in_progress' | 'completed' | 'cancelled'
      booking_status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'disputed' | 'cancelled'
      payment_status: 'deposit_paid' | 'fully_paid' | 'refunded' | 'pending'
      category_type: 'photography' | 'videography' | 'social_media' | 'editing' | 'influencer' | 'content_creation'
      notification_type: 'booking' | 'message' | 'payment' | 'kyc' | 'match' | 'review' | 'general'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
